apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress
  namespace: gajendra
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: ires-frontend
            port:
              number: 80
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: ires-backend
            port:
              number: 8000
      - path: /mongo
        pathType: Prefix
        backend:
          service:
            name: mongo-express
            port:
              number: 8081
